### ISSUE TITLE
Api Not Working

### ISSUE THREAD

**Issue by Rahulsingh8480** [shashankktiwariii/anikatsu#1]
Hi Tiwariji.

I tried everything. Also put new apiURL but new content is not showing. May be the data is not getting extracted. Please help me.

**Comment by MoeZilla** [comment]
:)

**Comment by shashankktiwariii** [comment]
@Rahulsingh8480 can u share more about your problem. May be on discord or telegram

**Comment by GioGio03** [comment]
@shashankktiwariii have you planned to make this project with pure javascript without using php, because I know js and maybe I'll be able to help you in the future. There are other things i would like to know, like to get the video of the anime you use gogoanime api and what does zoro.to use?

**Comment by shashankktiwariii** [comment]
zoro.to does nothing and for video I use gogoanime and for episode title I use anilist and mal

**Comment by GioGio03** [comment]
> zoro.to does nothing and for video I use gogoanime and for episode title I use anilist and mal

Alright but you will keep this project with php?

**Comment by shashankktiwariii** [comment]
yep
