### ISSUE TITLE
Getting the errors on UI as well as on home page

### ISSUE THREAD

**Issue by ishqDehlvi** [shashankktiwariii/anikatsu#13]
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/33024370/230788427-62de9fe7-fc74-4282-a056-cd325badc3a2.png">

OS: OsX

**Comment by ishqDehlvi** [comment]
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/33024370/230788470-3c67fd1f-bc6e-49db-ae6b-e57381bed1bd.png">

**Comment by shashankktiwariii** [comment]
@ishqDehlvi update your localhost url accordingly in _config.php

**Comment by ishqDehlvi** [comment]
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/33024370/230959910-df5aab69-29f6-45c6-ac14-9b0891738c82.png">
when I used this code and added the files to root of htdocs I am getting this

`
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/33024370/230960084-f8b8f453-4eab-4d35-98cc-cf7c3438870e.png">
`

but when I am clicking to any button I am getting this error
 `
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/33024370/230960205-aa00749c-2af4-41cc-ba45-5f2f016d1a0d.png">
`

**Comment by ishqDehlvi** [comment]
img width="1470" alt="image" src="https://user-images.githubusercontent.com/33024370/230960084-f8b8f453-4eab-4d35-98cc-cf7c3438870e.png

**Comment by ishqDehlvi** [comment]
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/33024370/230960460-42d8e61c-9d02-45de-a87b-3ccacf62ed86.png">

**Comment by ishqDehlvi** [comment]
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/33024370/230960679-84636999-f27c-457c-abaf-b3074afcaa8a.png">

**Comment by shashankktiwariii** [comment]
First, enable the apache rewrite module:

sudo a2enmod rewrite
you need to change in apache2.conf no need to change in sites-available

sudo gedit /etc/apache2/apache2.conf
Original

<Directory /var/www/>
     Options Indexes FollowSymLinks
     AllowOverride None
     Require all granted
</Directory>
To

<Directory /var/www/>
    Options Indexes FollowSymLinks
    AllowOverride all
    Require all granted
</Directory>
And restart apache2

sudo service apache2 restart

**Comment by shashankktiwariii** [comment]
https://stackoverflow.com/a/71874151 
refer to thiis

**Comment by ishqDehlvi** [comment]
I have followed that stackoverflow but I am getting error.
Can you have a look please??
http://54.208.202.120/

OS: Ubuntu
Aws ec2

**Comment by ishqDehlvi** [comment]
hosting done but there is an issue in the website as it's not loading can you have a look please.

https://ec2-44-206-237-139.compute-1.amazonaws.com/home
