### ISSUE TITLE
tried ruining on http://localhost:8888/

### ISSUE THREAD

**Issue by misles** [shashankktiwariii/anikatsu#2]
now links are working
![image](https://user-images.githubusercontent.com/23274732/191779960-d6ac9b08-95db-4e07-9933-6fc0287314cc.png)

**Comment by shashankktiwariii** [comment]
@misles go to php/info.php 
and change //{$_SERVER['SERVER_NAME']} to http://localhost:8888

**Comment by misles** [comment]
Thank you the UI came live but the links and the episodes are not working
![image](https://user-images.githubusercontent.com/23274732/191969753-8c568e5c-6ddc-4ae3-9130-d35cb7573abc.png)

**Comment by shashankktiwariii** [comment]
@misles actually in locolhost there is no use of .htaccess fileee.. Try enable it or host the website on a hosting server

**Comment by misles** [comment]
https://animehello.herokuapp.com/

the links and the episodes are not working
i have uploaded with out changes

**Comment by shashankktiwariii** [comment]
@misles https://heroku.com/deploy?template=https://github.com/shashankktiwariii/anikatsu/tree/main

Try deploying using this link 

Whenever you are hosting any site manually, pls recheck the presence of  . htaccess file

**Comment by misles** [comment]
thank you its working
