### ISSUE TITLE
Would be great if you add an admin panel.

### ISSUE THREAD

**Issue by enroj121d** [shashankktiwariii/anikatsu#3]
Would be great if you add an admin panel.

**Comment by DavidChriss** [comment]
1+ And database if possible for peoples qho want to create account

**Comment by shashankktiwariii** [comment]
@DavidChriss @enroj121d after 50 stars. xD

**Comment by DavidChriss** [comment]
Current 15 😔

**Comment by miffin2** [comment]
lutfem admın panelı eklermısın lutfen

**Comment by enroj121d** [comment]
> @DavidChriss @enroj121d after 50 stars. xD

seems reasonable we almost hit them.
