### ISSUE TITLE
Absolute banger !! Why ads tho? Use hls, mp4 scraped links from api.

### ISSUE THREAD

**Issue by animemandir** [shashankktiwariii/anikatsu#3]
If I knew php I would have made it with no ads. Make it with no ads vro.

riimuris api has options for video file links.

**Comment by shashankktiwariii** [comment]
@animemandir it's adless vro..... Disqus is messing up

**Comment by animemandir** [comment]
Only anikatsu server has no ads, but the other two listed are flooded with ads.
I suggest look into chirag-droid's animeflix project. 
Also, plz use hls streaming. It's nice.

**Comment by shashankktiwariii** [comment]
@animemandir ohhh okyyy bro... Thanks for the suggestion ❤

**Comment by riimuru** [comment]
>Also, plz use hls streaming. It's nice.
@animemandir he's using hls streaming already.

**Comment by animemandir** [comment]
> ohhh okyyy bro... Thanks for the suggestion ❤

btw, how much did you modify riimuru's api? 
I can I see the source?

**Comment by animemandir** [comment]
Hey, how to add a html home page and change routing to /home like you did in you production version

**Comment by shashankktiwariii** [comment]
> > ohhh okyyy bro... Thanks for the suggestion heart
> 
> btw, how much did you modify riimuru's api? can I see the source? Plz gib

Have a look https://replit.com/@shashankktiwari/anikatsu

**Comment by shashankktiwariii** [comment]
@animemandir Already Added Check Latest Commit
