### ISSUE TITLE
Source code player

### ISSUE THREAD

**Issue by AdsCity** [shashankktiwariii/anikatsu#5]
Hi,
Can u publish code of player.anikatsu.me

Tks

**Comment by shashankktiwariii** [comment]
Sorry, But I can't publish the code of player.anikatsu.me

**Comment by AdsCity** [comment]
> Sorry, But I can't publish the code of player.anikatsu.me

Tks u. but I see that the source code is not being updated to the latest version

**Comment by shashankktiwariii** [comment]
@AdsCity  I'll update it after 50 stars

**Comment by AdsCity** [comment]
> @AdsCity I'll update it after 50 stars

Tks u. Find way to promote it

**Comment by NerdsForGaming** [comment]
isnt player.anikatsu.me just a reskin of plyr?

**Comment by InstaTechHD** [comment]
Is it?

**Comment by shashankktiwariii** [comment]
jwplayer
