### ISSUE TITLE
Option to force certain episodes to defined stream

### ISSUE THREAD

**Issue by Awqre** [shashankktiwariii/anikatsu#7]
I think it might be useful if you add a template to the API for providing alternative video sources if desired. As far as I can tell right now there's no way to do this without significant editing of the design.

**Comment by shashankktiwariii** [comment]
Suree! Nice Idea

**Comment by animemandir** [comment]
IDK why the api is not working on any hosting. How did you host api.anikatsu? I saw your replit but when I forked it, it didn't work.

**Comment by Awqre** [comment]
> IDK why the api is not working on any hosting. How did you host api.anikatsu? I saw your replit but when I forked it, it didn't work.

I forked the replit and it worked fine

**Comment by shashankktiwariii** [comment]
> IDK why the api is not working on any hosting. How did you host api.anikatsu? I saw your replit but when I forked it, it didn't work.

What error

**Comment by animemandir** [comment]
> What error
Didn't run on local, didn't run on vps. cmd - `npm start`

downloaded zip file from repl. repl fork worked tho, but local ain't

**Comment by animemandir** [comment]
> What error

nvm fixed those, is there a failsafe in anikatsu's code that only your api.anikatsu url would work on it? 😂 cuz I hosted it but the php site doesn't fetch data from it? the api works, but site aint fetching it.

**Comment by shashankktiwariii** [comment]
@animemandir Lol.. I have updated the api https://github.com/shashankktiwariii/anikatsu-api
Now Try 
>npm i 
>npm start

And make sure you don't include slash ( / ) sign at last of API url while linking
