### ISSUE TITLE
Puedes agregar panel admin ? 

### ISSUE THREAD

**Issue by Raider7v7** [shashankktiwariii/anikatsu#8]
Si podrias ? Quiero subir mis propios animes

**Comment by shashankktiwariii** [comment]
@Raider7v7 Can the conversation be in English!?

**Comment by Awqre** [comment]
Their question was the same as mine about sourcing videos ourselves but specifically they want to upload their own through an admin panel.

**Comment by shashankktiwariii** [comment]
@Awqre Ohh Okyyyy 
For that i'll code a new project
